import unittest
import pytz
from datetime import timedelta, datetime
from format_timedelta import format_timedelta, calculate_shabbat


class FormatTimedeltaCase(unittest.TestCase):
    def test_formatting(self):
        td = timedelta(days=3, hours=22, minutes=52, seconds=53)
        self.assertEqual('через 3 дня 22 часа 52 минуты', format_timedelta(td))
        td = timedelta(days=1, hours=21, minutes=51)
        self.assertEqual('через 1 день 21 час 51 минуту', format_timedelta(td))
        td = timedelta(days=5, hours=5, minutes=5)
        self.assertEqual('через 5 дней 5 часов 5 минут', format_timedelta(td))
        td = timedelta(days=7, hours=7, minutes=7)
        self.assertEqual('через 7 дней 7 часов 7 минут', format_timedelta(td))
        td = timedelta(days=0, hours=1, minutes=21)
        self.assertEqual('через 1 час 21 минуту', format_timedelta(td))
        td = timedelta(days=11, hours=11, minutes=11)
        self.assertEqual('через 11 дней 11 часов 11 минут', format_timedelta(td))
        td = timedelta(days=12, hours=12, minutes=12)
        self.assertEqual('через 12 дней 12 часов 12 минут', format_timedelta(td))
        td = timedelta(days=6, hours=0, minutes=27)
        self.assertEqual('через 6 дней 27 минут', format_timedelta(td))
        td = timedelta(days=3, hours=4, minutes=0)
        self.assertEqual('через 3 дня 4 часа', format_timedelta(td))
        td = timedelta(days=5, hours=0, minutes=0, seconds=5)
        self.assertEqual('через 5 дней 5 секунд', format_timedelta(td))
        td = timedelta(days=1, hours=0, minutes=0)
        self.assertEqual('через 1 день', format_timedelta(td))
        td = timedelta(days=0, hours=1, minutes=1)
        self.assertEqual('через 1 час 1 минуту', format_timedelta(td))
        td = timedelta(days=0, hours=0, minutes=50)
        self.assertEqual('через 50 минут', format_timedelta(td))
        td = timedelta(days=0, hours=0, minutes=3)
        self.assertEqual('через 3 минуты', format_timedelta(td))
        td = timedelta(days=0, hours=0, minutes=0, seconds=59)
        self.assertEqual('через 59 секунд', format_timedelta(td))
        td = timedelta(days=0, hours=0, minutes=0, seconds=42)
        self.assertEqual('через 42 секунды', format_timedelta(td))
        td = timedelta(days=0, hours=0, minutes=0, seconds=22)
        self.assertEqual('через 22 секунды', format_timedelta(td))
        td = timedelta(days=0, hours=0, minutes=0, seconds=21)
        self.assertEqual('через 21 секунду', format_timedelta(td))
        td = timedelta(days=0, hours=0, minutes=0, seconds=12)
        self.assertEqual('через 12 секунд', format_timedelta(td))
        td = timedelta(days=0, hours=0, minutes=0, seconds=11)
        self.assertEqual('через 11 секунд', format_timedelta(td))
        td = timedelta(days=0, hours=0, minutes=0, seconds=3)
        self.assertEqual('через 3 секунды', format_timedelta(td))
        td = timedelta(days=0, hours=0, minutes=0, seconds=1)
        self.assertEqual('через 1 секунду', format_timedelta(td))

    def test_shabbat(self):
        tz = pytz.timezone('Asia/Jerusalem')
        now = datetime(year=2021, month=3, day=15, tzinfo=tz)
        self.assertEqual('через 4 дня 18 часов 11 минут', calculate_shabbat(now))
        now = datetime(year=2021, month=3, day=18, tzinfo=tz)
        self.assertEqual('через 1 день 18 часов 11 минут', calculate_shabbat(now))
        now = datetime(year=2021, month=3, day=18, hour=18, minute=11, tzinfo=tz)
        self.assertEqual('через 1 день 4 секунды', calculate_shabbat(now))
        now = datetime(year=2021, month=3, day=18, hour=18, minute=11, second=4, tzinfo=tz)
        self.assertEqual('через 1 день', calculate_shabbat(now))
        now = datetime(year=2021, month=3, day=19, hour=18, minute=11, second=4, tzinfo=tz)
        self.assertEqual('ебать, шаббат', calculate_shabbat(now))
        now = datetime(year=2021, month=3, day=19, hour=17, minute=11, second=4, tzinfo=tz)
        self.assertEqual('через 1 час', calculate_shabbat(now))
        now = datetime(year=2021, month=3, day=19, hour=17, minute=10, second=0, tzinfo=tz)
        self.assertEqual('через 1 час 1 минуту', calculate_shabbat(now))
        now = datetime(year=2021, month=3, day=19, hour=18, minute=10, second=0, tzinfo=tz)
        self.assertEqual('через 1 минуту', calculate_shabbat(now))
        now = datetime(year=2021, month=3, day=19, hour=18, minute=11, second=0, tzinfo=tz)
        self.assertEqual('через 4 секунды', calculate_shabbat(now))
        now = datetime(year=2021, month=3, day=20, hour=18, minute=11, second=0, tzinfo=tz)
        self.assertEqual('ебать, шаббат', calculate_shabbat(now))
        now = datetime(year=2021, month=3, day=20, hour=20, minute=11, second=0, tzinfo=tz)
        self.assertEqual('бля шаббат кончился', calculate_shabbat(now))
        now = datetime(year=2021, month=3, day=21, hour=18, minute=11, second=0, tzinfo=tz)
        self.assertEqual('через 5 дней 4 минуты', calculate_shabbat(now))
        now = datetime(year=2021, month=3, day=22, hour=18, minute=11, second=0, tzinfo=tz)
        self.assertEqual('через 4 дня 4 минуты', calculate_shabbat(now))


if __name__ == '__main__':
    unittest.main()
