name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
      -
        name: Login to Github Actions
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
      -
        name: Build and push
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          pull: true
          push: true
          tags: ghcr.io/graynk/bondobot:latest
